config:
  azure-native:location: westus3
  cst8918-a03-infra:appPath: ../
  cst8918-a03-infra:containerPort: '80'
  cst8918-a03-infra:publicPort: '80'
  cst8918-a03-infra:cpu: '1'
  cst8918-a03-infra:memory: '2'
  cst8918-a03-infra:prefixName: 'cst8918a03duan0027'
  cst8918-a03-infra:imageTag: v0.3.0
  cst8918-a03-infra:weatherApiKey:
    secure: AAABANJ/63SmZJpeepMWWqNoUkMeltay/hVaIh1Y9tnnB5vwI7/MH/v2mlwvi3UoIYQufQhFMK2T0yuhahiOsg==
